version: "3"
services:
  postgres:
    image: 1maa/postgres:10-alpine
    environment:
      - POSTGRES_DB=project
    ports:
      - "127.0.0.1:2345:5432"
  nginx:
    image: nginx:1.13-alpine
    depends_on:
      - fpm
    networks:
      default:
        aliases:
          - project.devel
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./public:/var/www/project.devel/public
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
  fpm:
    image: 1maa/php-dev:7.2
    volumes:
      - .:/var/www/project.devel
    working_dir: /var/www/project.devel
  phpstorm_test_runner:
    image: 1maa/php-dev:7.2
    volumes:
      - .:/var/www/project.devel
    working_dir: /var/www/project.devel
