version: "3"
services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
  fpm:
    image: 1maa/php-dev:7.2
    volumes:
      - .:/var/www/ecsdebu.devel
